In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(69)

## 1. How likely is it that you roll doubles when rolling two dice?

In [3]:
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
rolls

array([[4, 2],
       [4, 3],
       [5, 2],
       ...,
       [2, 4],
       [2, 4],
       [2, 1]])

In [4]:
pd.DataFrame(rolls)

0  1
0     4  2
1     4  3
2     5  2
3     2  1
4     2  1
...  .. ..
9995  1  2
9996  2  2
9997  2  4
9998  2  4
9999  2  1

[10000 rows x 2 columns]

In [8]:
pd.DataFrame(rolls).apply(lambda row: row.values[0] == row.values[1], axis = 1).mean()

# 16.6% to roll doubles when rolling two dice

0.1666

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [24]:
# method 1
n_trails = nrows = 10_000
n_flip = ncols = 8

coins = np.random.choice([0,1], size= (n_trails, n_flip))
coins

array([[0, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 1, 1]])

In [27]:
(coins.sum(axis=1) == 3).mean()

# 21.4% to get exactly 3 heads

0.2141

In [33]:
(coins.sum(axis=1) > 3).mean()

# 64.5% to get more than 3 heads

0.6454

In [23]:
# method 2
n_trails = nrows = 10_000
n_flip = ncols = 8

coins = np.random.choice(['head','tail'], size= (n_trails, n_flip))
coins
(pd.DataFrame(coins).apply(counthead,axis=1)==3).mean()

0.2217

In [14]:
def counthead(row):
    count = 0
    for x in range(0,8):
        if row[x] =='head':
            count +=1
    return count

In [29]:
# method 3 - using lambda function
pd.DataFrame(coins).apply(lambda row: row.values.sum()==3, axis=1)

0       False
1       False
2       False
3       False
4        True
        ...  
9995     True
9996     True
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [31]:
# 0 = Web development cohort
# 1 = data science cohort

n_trails = nrows = 10_000
n_flip = ncols = 2
cohort = np.random.choice([0,0,0,1], size=(n_trails, n_flip))
cohort

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [1, 1],
       [1, 0],
       [0, 0]])

In [32]:
(cohort.sum(axis=1)==2).mean()

# 6.5% to drive past both have data science student

0.0646

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values
- `np.random.normal`: generates numbers from a normal distribution with a specified mean and standard deviation

In [55]:
# avg = 3 poptarts/day; std = 1.5
poptarts = np.random.normal(3, 1.5, (10_000, 4))
poptarts

array([[0.94023965, 1.54737152, 0.92380386, 2.62678278],
       [1.97109208, 1.99150654, 2.52983251, 0.98007653],
       [3.03565419, 1.67375296, 4.19678909, 2.81518052],
       ...,
       [3.59870923, 2.06507432, 3.88815815, 2.31008149],
       [4.95851636, 2.81947826, 0.61217456, 4.98921801],
       [1.65979459, 6.63601868, 1.11419101, 2.8716704 ]])

In [56]:
(poptarts.sum(axis = 1)<16).mean()

# 90.6% will have poptarts at Friday afternoon

0.906

In [171]:
poptarts = np.random.normal(3, 1.5, (10_000,5))
hungry = pd.DataFrame(poptarts)

In [174]:
hungry.apply(lambda row: row.values.sum()<=17, axis = 1).mean()

0.7181

## 5. Compare Heights

#### Men have an average height of 178 cm and standard deviation of 8cm.
#### Women have a mean of 170, sd = 6cm.
#### Since you have means and standard deviations, you can use np.random.normal to generate observations.
#### If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [77]:
# mavg = 178, mstd = 8
# favg = 170, fstd = 6
male = pd.DataFrame(np.random.normal(178, 8, size=(10000, 1)))
female = pd.DataFrame(np.random.normal(170, 6, size=(10000, 1)))


In [167]:
compare = male<female
compare

0
0     False
1     False
2      True
3     False
4     False
...     ...
9995  False
9996  False
9997   True
9998  False
9999  False

[10000 rows x 1 columns]

In [170]:
compare.sum() / 10000

# 20.8% woman is taller than man

0    0.2084
dtype: float64

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.
#### a. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [176]:
p_corrupted = 1/250
nstudents = 50
n_trails = 10_000
data = np.random.random(size = (n_trails, nstudents))
data

array([[0.25067118, 0.45482931, 0.67501045, ..., 0.64410802, 0.68166964,
        0.53915709],
       [0.17076358, 0.59644655, 0.42197261, ..., 0.5900433 , 0.40674694,
        0.02893866],
       [0.77255302, 0.5028885 , 0.27758985, ..., 0.19787559, 0.78303895,
        0.28503257],
       ...,
       [0.10068058, 0.94319517, 0.30688897, ..., 0.38844208, 0.6096441 ,
        0.23940465],
       [0.38217502, 0.28137467, 0.0732007 , ..., 0.59929693, 0.61355369,
        0.93385197],
       [0.81360654, 0.42383803, 0.93231252, ..., 0.40280028, 0.18583774,
        0.26343396]])

In [97]:
1/250

0.004

In [104]:
issues = data < p_corrupted
issues

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [105]:
(issues.sum(axis = 1)==0).mean()

# 90% no one has installation issues

0.8099

In [183]:
# Using np.random.choice

dt = np.random.choice([0,1],p=[0.996, 0.004], size = (n_trails, nstudents))
dt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [182]:
noissues = dt.sum(axis=1).mean()
noissues

0.2042

In [106]:
# 100 students

p_corrupted = 1/250
nstudents = 100
n_trails = 10_000
data = np.random.random(size = (n_trails, nstudents))
data

array([[0.25461953, 0.82216057, 0.73381185, ..., 0.9386115 , 0.12475172,
        0.58225353],
       [0.15793089, 0.18008194, 0.77231616, ..., 0.6243313 , 0.80091793,
        0.11649688],
       [0.76740778, 0.96846861, 0.44808038, ..., 0.71207643, 0.40088515,
        0.34206653],
       ...,
       [0.00922345, 0.65920629, 0.11198205, ..., 0.46645072, 0.70933596,
        0.28268712],
       [0.74460991, 0.19181576, 0.74788782, ..., 0.90262983, 0.70727326,
        0.67327224],
       [0.36155889, 0.70145535, 0.04606351, ..., 0.92863824, 0.34744474,
        0.1927192 ]])

In [107]:
issues = data < p_corrupted
(issues.sum(axis = 1)== 0).mean()

# 67.7%

0.6766

In [184]:
# Using np.random.choice

p_corrupted = 1/250
nstudents = 100
n_trails = 10_000
data = np.random.random(size = (n_trails, nstudents))
data
dt = np.random.choice([0,1],p=[0.996, 0.004], size = (n_trails, nstudents))
dt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [185]:
noissues = dt.sum(axis=1).mean()
noissues

# 38.1%

0.3808

#### b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [108]:
p_corrupted = 1/250
nstudents = 150
n_trails = 10_000
data = np.random.random(size = (n_trails, nstudents))
data

array([[0.93038167, 0.15846334, 0.61708632, ..., 0.36255069, 0.11543737,
        0.83195431],
       [0.12972672, 0.58263847, 0.35937911, ..., 0.13065545, 0.92202627,
        0.08207998],
       [0.59843228, 0.74348594, 0.3979209 , ..., 0.00490505, 0.76760772,
        0.12509687],
       ...,
       [0.21882023, 0.3893025 , 0.02309949, ..., 0.16291545, 0.59537997,
        0.8379657 ],
       [0.77373964, 0.08945353, 0.71278706, ..., 0.63204928, 0.16861988,
        0.61150782],
       [0.85430375, 0.85974638, 0.23243823, ..., 0.70396908, 0.81028371,
        0.6448604 ]])

In [109]:
issues = data >= p_corrupted
(issues.sum(axis = 1)>=1).mean()

# 100%

1.0

#### c. How likely is it that 450 students all download anaconda without an issue?

In [110]:
p_corrupted = 1/250
nstudents = 450
n_trails = 10_000
data = np.random.random(size = (n_trails, nstudents))
data

array([[0.3967653 , 0.78766487, 0.78921138, ..., 0.68036229, 0.04752164,
        0.218887  ],
       [0.57108059, 0.88779292, 0.80899   , ..., 0.38844469, 0.80462944,
        0.87615536],
       [0.94018567, 0.50810289, 0.0938258 , ..., 0.51215016, 0.75663446,
        0.99286474],
       ...,
       [0.90809166, 0.83384771, 0.8992812 , ..., 0.03055744, 0.22826676,
        0.7896096 ],
       [0.66140644, 0.84302988, 0.96639877, ..., 0.10237856, 0.85747097,
        0.6603968 ],
       [0.73805491, 0.19241195, 0.6297689 , ..., 0.07667931, 0.70743724,
        0.24588701]])

In [111]:
issues = data < p_corrupted
(issues.sum(axis = 1)==0).mean()

# 16.6%

0.1658

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park.
#### However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [115]:
p_food = 0.7
data = np.random.random(size = (10_000, 3))
data

array([[0.22644686, 0.07579093, 0.92674171],
       [0.66291615, 0.66972004, 0.82499957],
       [0.12931396, 0.56434311, 0.65205153],
       ...,
       [0.76517611, 0.42670576, 0.42444335],
       [0.43657874, 0.59982208, 0.30085228],
       [0.77265997, 0.10174265, 0.2098241 ]])

In [117]:
nofood = data<p_food
nofood

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True,  True],
       ...,
       [False,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

In [118]:
(nofood.sum(axis=1)==3).mean()

# 34.2%

0.3421

#### How likely is it that a food truck will show up sometime this week?

In [119]:
data = np.random.random(size = (10_000, 5))

In [122]:
foodhere = data > p_food
(foodhere.sum(axis=1)>=1).mean()

# 83%

0.8304

## 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [158]:
people = np.random.uniform(1, 366, size = (10_000, 23)).astype(np.int32)
people

array([[210,  37, 228, ..., 226, 251,  70],
       [159, 164, 199, ..., 204, 130, 308],
       [108,  55, 293, ..., 212,  28, 355],
       ...,
       [ 53, 169, 222, ..., 102, 313, 312],
       [226, 334,  97, ..., 294, 341, 124],
       [240, 333, 244, ..., 150,  65, 267]], dtype=int32)

In [162]:
newppl=pd.DataFrame(people)
newppl

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     210   37  228   99  207   67  185  103  165  136  ...  271  174   76   
1     159  164  199   19  348  233   73  316  317  264  ...  212  305  111   
2     108   55  293  312  351  160  273  230  255  294  ...   35   67  155   
3     314  354  251  212   58  202   57  149   36  208  ...  305  168  311   
4     355  277  101  192  292  117  281   28   64  252  ...  129   58   17   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995    9   96  221  224   38  198  206  276  162  293  ...  316  224  155   
9996  175  289  310  101   52  186  327  301  305  217  ...  258  165   50   
9997   53  169  222  272  338   39  205  279  209  234  ...  162   24  182   
9998  226  334   97   95  157  324  217  131  336  135  ...  315  196   33   
9999  240  333  244  354  332  219  144   60  306  123  ...  279  108  305   

       16   17   18   19   20   21   22  
0      50  184  231  317  226  251   70  
1     216  361  128   89  204  130  308  
2     168  177    3  290  212   28  355  
3     313  214  224  352  154   73  358  
4     356  187   58  146  179  114   36  
...   ...  ...  ...  ...  ...  ...  ...  
9995  303   97  295   35   57  329   76  
9996  269  196  293  340  240  132   61  
9997   92  138  205  257  102  313  312  
9998  242  259  234  298  294  341  124  
9999  141   61   39  296  150   65  267  

[10000 rows x 23 columns]

In [164]:
newppl=pd.DataFrame(people).nunique(axis=1)
newppl

0       23
1       23
2       23
3       23
4       22
        ..
9995    22
9996    23
9997    22
9998    23
9999    23
Length: 10000, dtype: int64

In [145]:
def contains_duplicates(X):
    seen = set()
    seen_add = seen.add
    for x in X:
        if (x in seen or seen_add(x)):
            return True
    return False

In [151]:
sharebd = pd.DataFrame(people).apply(contains_duplicates, axis = 1)
sharebd

0        True
1        True
2        True
3       False
4       False
        ...  
9995     True
9996    False
9997     True
9998     True
9999     True
Length: 10000, dtype: bool

In [154]:
(sharebd.sum()).mean()/10000

# 50.2%

0.5021

#### What if it's 20 people?

In [155]:
people = np.random.uniform(0, 366, size = (10_000, 20)).astype(np.int32)
sharebd = pd.DataFrame(people).apply(contains_duplicates, axis = 1)
(sharebd.sum()).mean()/10000

# 41%

0.4111

#### 40?

In [156]:
people = np.random.uniform(0, 366, size = (10_000, 40)).astype(np.int32)
sharebd = pd.DataFrame(people).apply(contains_duplicates, axis = 1)
(sharebd.sum()).mean()/10000

0.8889