In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(69)

## 1. How likely is it that you roll doubles when rolling two dice?

In [19]:
# method 1
n_trials = nrows = 10_000
n_dice = ncols = 2

rolls = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
rolls

array([[1, 4],
       [4, 5],
       [2, 2],
       ...,
       [4, 6],
       [2, 1],
       [4, 6]])

In [4]:
pd.DataFrame(rolls)

0  1
0     4  2
1     4  3
2     5  2
3     2  1
4     2  1
...  .. ..
9995  1  2
9996  2  2
9997  2  4
9998  2  4
9999  2  1

[10000 rows x 2 columns]

In [20]:
pd.DataFrame(rolls).apply(lambda row: row.values[0] == row.values[1], axis = 1).mean()

# 16.7% to roll doubles when rolling two dice

0.1668

In [ ]:
# method  2

(rollls[:,0] == rolls[:,1]).mean()

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [24]:
# method 1

n_trails = nrows = 10_000
n_flip = ncols = 8

coins = np.random.choice([0,1], size= (n_trails, n_flip))
coins

array([[0, 1, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 1, 1],
       [0, 1, 0, ..., 0, 0, 1],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [1, 0, 1, ..., 0, 1, 1]])

In [27]:
(coins.sum(axis=1) == 3).mean()

# 21.4% to get exactly 3 heads

0.2141

In [33]:
(coins.sum(axis=1) > 3).mean()

# 64.5% to get more than 3 heads

0.6454

In [23]:
# method 2

n_trails = nrows = 10_000
n_flip = ncols = 8

coins = np.random.choice(['head','tail'], size= (n_trails, n_flip))
coins
(pd.DataFrame(coins).apply(counthead,axis=1)==3).mean()

0.2217

In [14]:
def counthead(row):
    count = 0
    for x in range(0,8):
        if row[x] =='head':
            count +=1
    return count

In [29]:
# method 3 - using lambda function
pd.DataFrame(coins).apply(lambda row: row.values.sum()==3, axis=1)

0       False
1       False
2       False
3       False
4        True
        ...  
9995     True
9996     True
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [31]:
# 0 = Web development cohort
# 1 = data science cohort

n_trails = nrows = 10_000
n_flip = ncols = 2
cohort = np.random.choice([0,0,0,1], size=(n_trails, n_flip))
cohort

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [1, 1],
       [1, 0],
       [0, 0]])

In [32]:
(cohort.sum(axis=1)==2).mean()

# 6.5% to drive past both have data science student

0.0646

In [21]:
# theoretical prob

0.25 * 0.25

0.0625

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values
- `np.random.normal`: generates numbers from a normal distribution with a specified mean and standard deviation

In [55]:
# method 1
# avg = 3 poptarts/day; std = 1.5

poptarts = np.random.normal(3, 1.5, (10_000,5))
hungry = pd.DataFrame(poptarts)

array([[0.94023965, 1.54737152, 0.92380386, 2.62678278],
       [1.97109208, 1.99150654, 2.52983251, 0.98007653],
       [3.03565419, 1.67375296, 4.19678909, 2.81518052],
       ...,
       [3.59870923, 2.06507432, 3.88815815, 2.31008149],
       [4.95851636, 2.81947826, 0.61217456, 4.98921801],
       [1.65979459, 6.63601868, 1.11419101, 2.8716704 ]])

In [174]:
hungry.apply(lambda row: row.values.sum()<=17, axis = 1).mean()

# 71.8% will have poptarts at Friday afternoon

0.7181

In [23]:
# method 2

pop = np.random.normal(3, 1.5, size =(10_000, 5))

array([False,  True,  True, ...,  True,  True,  True])

In [24]:
(pop.sum(axis = 1) < 17).mean()

0.7284

## 5. Compare Heights

#### Men have an average height of 178 cm and standard deviation of 8cm.
#### Women have a mean of 170, sd = 6cm.
#### Since you have means and standard deviations, you can use np.random.normal to generate observations.
#### If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [77]:
# mavg = 178, mstd = 8
# favg = 170, fstd = 6
male = pd.DataFrame(np.random.normal(178, 8, size=(10000, 1)))
female = pd.DataFrame(np.random.normal(170, 6, size=(10000, 1)))


In [167]:
compare = male<female
compare

0
0     False
1     False
2      True
3     False
4     False
...     ...
9995  False
9996  False
9997   True
9998  False
9999  False

[10000 rows x 1 columns]

In [170]:
compare.sum() / 10000

# 20.8% woman is taller than man

0    0.2084
dtype: float64

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.
#### a. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

In [27]:
# Using np.random.choice

p_corrupted = 1/250
nstudents = 50
n_trails = 10_000

dt = np.random.choice([0,1],p=[0.996, 0.004], size = (n_trails, nstudents))
dt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [28]:
noissues = (dt.sum(axis=1)==0).mean()
noissues

# 82.1%

0.8211

In [3]:
# Using np.random.choice

p_corrupted = 1/250
nstudents = 100
n_trails = 10_000

dt = np.random.choice([0,1],p=[0.996, 0.004], size = (n_trails, nstudents))
dt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [4]:
noissues = (dt.sum(axis=1)==0).mean()
noissues

# 67.1%

0.6709

#### b. What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [29]:
p_corrupted = 1/250
nstudents = 150
n_trails = 10_000

dt = np.random.choice([0,1],p=[0.996, 0.004], size = (n_trails, nstudents))
dt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [30]:
issue = (dt.sum(axis = 1)>=1).mean()
issue

# 44.9%

0.4491

#### c. How likely is it that 450 students all download anaconda without an issue?

In [8]:
p_corrupted = 1/250
nstudents = 450
n_trails = 10_000
dt = np.random.choice([0,1],p=[0.996, 0.004], size = (n_trails, nstudents))
dt

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
(dt.sum(axis = 1)==0).mean()

# 16.9%

0.1686

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park.
#### However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [32]:
trucks = np.random.choice([0,1], size=(10000,3), p= [0.3, 0.7])

In [33]:
(trucks.sum(axis=1)==0).mean()

# 2.6% to not see a food truck in 3 days

0.0265

#### How likely is it that a food truck will show up sometime this week?

In [34]:
food = np.random.choice([0,1], size=(10000,2), p= [0.3, 0.7])

In [35]:
(food.sum(axis=1)>=1).mean()

# 91%

0.9114

## 8. If 23 people are in the same room, what are the odds that two of them share a birthday? 

In [10]:
# Using dataframe

people = np.random.uniform(1, 366, size = (10_000, 23)).astype(np.int32)
people

array([[244, 213, 185, ..., 335, 307, 222],
       [212, 288, 362, ...,  75, 280,  99],
       [300, 206, 235, ..., 179, 217, 157],
       ...,
       [ 29, 353, 255, ..., 364, 132, 354],
       [ 54, 255, 147, ..., 340, 287, 318],
       [ 15,  95, 332, ..., 159, 327, 277]], dtype=int32)

In [11]:
newppl=pd.DataFrame(people)
newppl

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     244  213  185  222  288  144  127  163  346  113  ...  291   52   10   
1     212  288  362  236  319  202  292  181  113  277  ...  120  137   20   
2     300  206  235  323  304  359  235  224  161  101  ...   10  229  308   
3     329   47   26  278  167   34  308   65   43  322  ...  360  307  175   
4     142  183   81   18  162   30    9  203  166  108  ...  112   33  334   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995  261  131   56  183   62  122  338   78  147   40  ...   56  201   39   
9996   27  254  175  164  262  122  151  147  141  217  ...  190  271  139   
9997   29  353  255  175  175  307  139   15  278  329  ...   20  276  244   
9998   54  255  147  261   74  301  183  324  334  198  ...  233  170  302   
9999   15   95  332   10   51  270  223  346  239  101  ...   36  282  142   

       16   17   18   19   20   21   22  
0     317  350    3  117  335  307  222  
1     133   92   26   95   75  280   99  
2      37  104  230   62  179  217  157  
3     184  313  148   56  276  350  279  
4     323   38  158  235  327   50  244  
...   ...  ...  ...  ...  ...  ...  ...  
9995  329  313   57   54  134  297  107  
9996  364   82  205  213  270   22   81  
9997   35   64   28  199  364  132  354  
9998  317  257  168  215  340  287  318  
9999  210  137  109  105  159  327  277  

[10000 rows x 23 columns]

In [12]:
newppl=pd.DataFrame(people).nunique(axis=1)
newppl

0       21
1       23
2       22
3       23
4       23
        ..
9995    22
9996    23
9997    22
9998    23
9999    23
Length: 10000, dtype: int64

In [16]:
share_bd = newppl<23
share_bd

0        True
1       False
2        True
3       False
4       False
        ...  
9995     True
9996    False
9997     True
9998    False
9999    False
Length: 10000, dtype: bool

In [18]:
share_bd.sum()/9999 * 100

# 51%

50.99509950995099

In [145]:
# Using a function

def contains_duplicates(X):
    seen = set()
    seen_add = seen.add
    for x in X:
        if (x in seen or seen_add(x)):
            return True
    return False

In [151]:
sharebd = pd.DataFrame(people).apply(contains_duplicates, axis = 1)
sharebd

0        True
1        True
2        True
3       False
4       False
        ...  
9995     True
9996    False
9997     True
9998     True
9999     True
Length: 10000, dtype: bool

In [154]:
(sharebd.sum()).mean()/10000

# 50.2%

0.5021

#### What if it's 20 people?

In [155]:
people = np.random.uniform(0, 366, size = (10_000, 20)).astype(np.int32)
sharebd = pd.DataFrame(people).apply(contains_duplicates, axis = 1)
(sharebd.sum()).mean()/10000

# 41%

0.4111

#### 40?

In [156]:
people = np.random.uniform(0, 366, size = (10_000, 40)).astype(np.int32)
sharebd = pd.DataFrame(people).apply(contains_duplicates, axis = 1)
(sharebd.sum()).mean()/10000

0.8889

## Mage Duel

Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

#### Simulate mage duels to answer who is the more powerful mage?


#### Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.

In [69]:
n_trials = nrows = 10_000
n_dice = ncols = 6

wizard = np.random.choice([1, 2, 3, 4], size = (n_trials, n_dice))
w_health = wizard.sum(axis=1)
w_health

array([18, 16, 19, ..., 17, 15, 12])

In [70]:
n_trials = nrows = 10_000
n_dice = ncols = 4
opposing = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
o_health = opposing.sum(axis=1)
o_health

array([13, 10, 12, ...,  9, 15, 10])

In [71]:
compare = (w_health-o_health) > (o_health-w_health)
compare.sum()/10_000

# 54.2% your wizard will have more health point left

0.5419

#### Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?

In [78]:
n_trials = nrows = 10
n_dice = ncols = 6

wizard = np.random.choice([1, 2, 3, 4], size = (n_trials, n_dice))
w_health = wizard.sum(axis=1)
w_health

array([17, 19, 16, 12, 13, 14, 16, 10, 14, 16])

In [79]:
n_trials = nrows = 10
n_dice = ncols = 4
opposing = np.random.choice([1, 2, 3, 4, 5, 6], size = (n_trials, n_dice))
o_health = opposing.sum(axis=1)
o_health

array([14, 11, 14, 14, 20,  9, 15, 12, 13, 16])

In [80]:
winner = (w_health-o_health) > (o_health-w_health) 
winner
winner.sum()/10

# answers: 70%, 50%, 50%, 60%

0.6

#### Do the results change much at 100 duels?

#### Now, simulate 10,000 mage duels. Is there a clear winner?